### ISSUE TITLE
DLM broken on kernel 5.10+

### ISSUE THREAD

**Issue by CkNoSFeRaTU** [bvanassche/scst#35] opened 2021-05-13 08:19 UTC
After [various set_fs() removal changes](https://lwn.net/Articles/832121/), especially [this commit](https://github.com/torvalds/linux/commit/4d03e3cc59828c82ee89ea6e27a2f3cdf95aaadf), kernel_read() is not supported without read_iter() fops. Which is the case for in-tree dlm module.
```
kernel read not supported for file cluster/comms/2/local (pid: 12345 comm: scst_uid)
kernel read not supported for file cluster/comms/1/local (pid: 12345 comm: scst_uid)
scst: ***ERROR***: scst_dlm_update_nodeids(test-01) failed: -22
```

**Comment by bvanassche** [comment] 2021-05-15 03:10
Please upgrade to a later version of the kernel since the following commits have been included in kernel version v5.10.11:
* https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/?id=6ce10b6481cd ("kernfs: implement ->read_iter"; upstream commit https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=4eaad21a6ac9865df7f31983232ed5928450458d).
* https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/?id=11167454e9cb ("kernfs: implement ->write_iter"; upstream commit https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=cc099e0b399889c6485c88368b19824b087c9f8c).

**Comment by CkNoSFeRaTU** [comment] 2021-05-16 17:49
It was tested on current Debian unstable kernel which is based on 5.10.28. So these patches were already included and not helping. I could re-test on latest vanilla kernel tomorrow and debug out exact cause. I believe the issue is that [scst uses kernel_read() call directly](https://github.com/bvanassche/scst/blob/master/scst/src/scst_dlm.c#L513). Though it just a guess as I didn't debugged the issue at all and just downgraded to latest 5.4 kernel.

**Comment by bvanassche** [comment] 2021-05-16 18:19
That's interesting. I had not yet tried to reproduce this issue but I will try to reproduce this issue myself.

**Comment by bvanassche** [comment] 2021-05-18 18:56
The commits I mentioned before affect the sysfs code. DLM uses configfs. The files for which reading fails are configfs files. configfs supports a .read method but not a .read_iter method:
```
const struct file_operations configfs_file_operations = {
	.read		= configfs_read_file,
	.write		= configfs_write_file,
	.llseek		= generic_file_llseek,
	.open		= configfs_open_file,
	.release	= configfs_release,
};
```
The .read method only supports transferring data to user space. SCST cannot allocate user space memory nor can it override the v5.10 or later kernel checks that verify whether an address is a user space address. The following commit removed the ability to modify `current->thread.addr_limit.seg`:  https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=47058bb54b57962b3958a936ddbc59355e4c5504

**Comment by CkNoSFeRaTU** [comment] 2021-05-19 07:11
Yeah, I digged the problem a bit on 5.12-rc2 kernel and came to the same conclusion. I didn't find a method to overcome this issue without convoluted hackery. So it seems the only solution is to pass the data through userspace intermediary daemon. Or wait and hope that configfs receives iter support akin to sysfs.

**Comment by bvanassche** [comment] 2021-05-19 15:52
I have started looking into modifying configfs. I think it will be less work to add .read_iter / .write_iter support to configfs compared to introducing an intermediary userspace daemon.

**Comment by bvanassche** [comment] 2021-05-20 03:55
For the configfs patch, see also https://lore.kernel.org/lkml/20210520034521.16102-1-bvanassche@acm.org/T/#u

**Comment by bvanassche** [comment] 2021-05-25 16:35
That patch has been staged for kernel v5.14. See also http://git.infradead.org/users/hch/configfs.git/log/refs/heads/for-next.

**Comment by bvanassche** [comment] 2021-09-07 00:46
Closing this ticket now that kernel v5.14 has been released.

**Closed by bvanassche** 2021-09-07 00:46 UTC
